baseURL: "https://ibrahim10002.github.io"
languageCode: "en-us"
title: "Portfolio gihHub MAZREK Ibrahim"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: AP
      name: AP et Projets
      title: AP et Projets
      url: /projets/
      weight: 1
    - identifier: Stages
      name: Stages
      title: Stages
      url: /stages/
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Portfolio Mazrek Ibrahim"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Hugo Profile" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Bonjour, je suis"
    title: "Ibrahim Mazrek."
    subtitle: "J'ai construit se site avec gitHub"
    content: "Je suis étudiant en bts SIO SLAM"
    image: /images/hero.svg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://example.com
        - icon: fab fa-x-twitter
          url: https://example.com
      customIcons:
        - icon: /fav.png
          url: "https://example.com"

  # About
  about:
    enable: true
    title: "A propos de moi "
    image: "/images/me.png"
    content: |-
      Je suis actuellement étudiant en bts sio slam au lycée bouchardon à chaumont, j'ai réaliser deux stages au cours de mon bts.

      J'ai développer différentes compétences dans différents language de programmation.
    skills:
      enable: true
      title: "Voici les language de programmation que je maitrise:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "Php"
        - "C#"
        - "Xml/Json"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Stage 2èm Année"
        company: "Les conchitas"
        companyUrl: "http://conchitas.fr"
        date: "14 Janvier - 02 Mars"
        featuredLink:
          enable: true
          name: "Voir le projet"
          url: "http://conchitas.fr/"
          info:
            enable: true
            content: J'ai réaliser un site dynamique pour ma 2em Année de BTS.
        content: "J'ai réaliser un site web dynamique pour ce stage [conchitas.fr.](http://conchitas.fr/) à Besançon."

      - job: "Stage 1er Année"
        company: "PressingVitaNeuf"
        companyUrl: "http://nicaise.lydie.free.fr/"
        date: "31 Mai - 01 Juillet"
        featuredLink:
          enable: true
          url: "http://nicaise.lydie.free.fr/"
        info:
          enable: true
          content: J'ai réaliser un site static pour ma 1er Année.
        content: J'ai réaliser un site web static pour ce stage [nicaise.lydie.free.fr.](http://nicaise.lydie.free.fr/) à Chaumont.


  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "BTS SIO BAC +2"
        school:
          name: "Lycée bouchardon, Chaumont"
          url: "https://lyc-bouchardon.monbureaunumerique.fr/"
        date: "2022 - 2024"
        content: BAC +2 SIO SLAM (Service Informatioque aux organisations option Service Logiciel et Applications Métiers) *En cours d'obtention*
        featuredLink:
          enable: true
          name: "Lien site"
          url: "https://lyc-bouchardon.monbureaunumerique.fr/"
            
      - title: "BAC STMG"
        school:
          name: "Lycée Joliot Curie, Romilly s/Seine"
          url: "https://lyc-joliot-curie-romilly.monbureaunumerique.fr/"
        date: "2018 - 2022"
        content: BACCALAUREAT STMG (Science et Technologies du Management. et de la Gestion enseignement) *Obtenu*
        featuredLink:
          enable: true
          name: "Lien site"
          url: "https://lyc-joliot-curie-romilly.monbureaunumerique.fr/"
          
      - title: "Brevet des collèges"
        school:
          name: "Collège Paul Langevin, Romilly s/Seine."
          url: "https://clg-langevin-romilly.monbureaunumerique.fr/"
        date: "2014 - 2018"
        content: Brevet des collèges *Obtenu*
        featuredLink:
          enable: true
          name: "Lien site"
          url: "https://clg-langevin-romilly.monbureaunumerique.fr/"

  # projects
  projects:
    enable: false
    # title: "Custom Name"
    items:
      - title: Application Gestion de responsables par services
        content: J'ai codé une application WPF permettant de gérer des responsables par service et ainsi de consulter leurs enfants.
        image: /images/projects/profile.png
        badges:
          - "C#"
          - "MySql"


      - title: Application Gestion des enfants et des activité
        content: J'ai codé une application WPF permettant de gérer des enfants et des activité et ainsi de consulter le parent d'un enfant.
        image: /images/projects/converter.jpg
        badges:
          - "C#"
          - "MySql"


      - title: Site web Conchitas
        content: J'ai codé un site web dynamique dans le cadre de mon stage de deuxième année, permettant de générer un devis selon les critère de nettoyage du client.
        image: /images/projects/profile2.jpg
        featured:
          name: Lien site
          link: http://conchitas.fr
        badges:
          - "Html"
          - "Css"
          - "PHP"
          - "Jquery"
          - "JavaScript"
          - "MySql"

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: Je répond aux mails, n'hésite pas à me contacter !
    btnName: Envoie moi un mail
    btnLink: mailto:imazrek@numerique-educatif.fr
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "Tout les droits sont réservés"
    pageNotFound: "Page on trouvé"
    emailText: "Check ce site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
